// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq1UbdUVX9KieqNnwbau-sr0C-LJKUEz4',
    appId: '1:1098248130962:web:a8c687cd548c814e30f14b',
    messagingSenderId: '1098248130962',
    projectId: 'rents-cars-affab',
    authDomain: 'rents-cars-affab.firebaseapp.com',
    storageBucket: 'rents-cars-affab.firebasestorage.app',
    measurementId: 'G-M9FE9Y4LQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqrERozLgJU1I-ngVOKLHxVszIvwD_HMY',
    appId: '1:1098248130962:android:6e92b1347d45f3af30f14b',
    messagingSenderId: '1098248130962',
    projectId: 'rents-cars-affab',
    storageBucket: 'rents-cars-affab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYIbj8--NK5DAArL9GR6xEp6wMscBI5sE',
    appId: '1:1098248130962:ios:03971d7c422a651a30f14b',
    messagingSenderId: '1098248130962',
    projectId: 'rents-cars-affab',
    storageBucket: 'rents-cars-affab.firebasestorage.app',
    iosBundleId: 'com.example.rentACarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYIbj8--NK5DAArL9GR6xEp6wMscBI5sE',
    appId: '1:1098248130962:ios:03971d7c422a651a30f14b',
    messagingSenderId: '1098248130962',
    projectId: 'rents-cars-affab',
    storageBucket: 'rents-cars-affab.firebasestorage.app',
    iosBundleId: 'com.example.rentACarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq1UbdUVX9KieqNnwbau-sr0C-LJKUEz4',
    appId: '1:1098248130962:web:e960fd39829f209e30f14b',
    messagingSenderId: '1098248130962',
    projectId: 'rents-cars-affab',
    authDomain: 'rents-cars-affab.firebaseapp.com',
    storageBucket: 'rents-cars-affab.firebasestorage.app',
    measurementId: 'G-TXHKB1MPK2',
  );
}
